### PR TITLE
ingestr: Use Xonsh 0.23.1

### LINKED ISSUE #6354: CalledProcessError: Command '['["rows"]']' returned non-zero exit status 1.
Hi there. First things first: Thanks a stack for conceiving and maintaining Xonsh.

Today, we found a nightly job on [CI/GHA failing](https://github.com/crate/cratedb-examples/actions/runs/24703335529/job/72251097865#step:4:2909) that uses Xonsh and most likely pulled the new release 0.23.0 that includes a few breaking changes.

Probably due to changes in GH-6159, we are receiving this exception now:
```python
Traceback (most recent call last):
  File "kafka-demo.xsh", line 226, in <module>
    main()
    
  File "kafka-demo.xsh", line 215, in main
    data.acquire().publish().load().display().verify()
    
  File "kafka-demo.xsh", line 149, in display
    pprint(query_cratedb('SELECT * FROM "kafka_demo" LIMIT 5;')["rows"])
    
  File "/home/runner/.local/share/uv/tools/xonsh/lib/python3.12/site-packages/xonsh/built_ins.py", line 565, in subproc_check_boolop
    raise subprocess.CalledProcessError(rtn, spec.args, output=output)
subprocess.CalledProcessError: Command '['["rows"]']' returned non-zero exit status 1.
```

Can we humbly ask about guidance how to rephrase the dictionary access at this spot with current and future versions of Xonsh? Please find a reference to the full code [here](https://github.com/crate/cratedb-examples/blob/e6dfff9/application/ingestr/kafka-demo.xsh#L142-L150).

### PR DESCRIPTION
**Pull request by anki-code**
Fix https://github.com/xonsh/xonsh/issues/6354

### CODE REVIEW

File: application/ingestr/test.sh [hunk 1]
```diff
@@ -20,7 +20,7 @@ function setup() {
 function test_kafka() {
   # Use specific version of Xonsh until #6354 is resolved.
   # https://github.com/xonsh/xonsh/issues/6354
```
Comment (amotl) [inline application/ingestr/test.sh]: Just a nit to also remove the comment.
```suggestion
```

**Review by amotl — APPROVED** [review]
That was fast. Thank you for the swift turnaround. 🌻
